### ISSUE TITLE
Implement READ_ONLY_SESSION / NO_MOODLE_COOKIES polling for better performance

### ISSUE THREAD

**Issue by brendanheywood** [marinaglancy/moodle-tool_realtime#2]
Split from #1 this is performance bonus points:

> each poll doesn't change any state on the server, ie no SESSION changes, and no writing of data

* [ ] As this is stateless we can write close the session immediately
* [ ] Turn on READ_ONLY_SESSION

* [ ] As a fallback we can possibly also use the require_user_key_login() with define('NO_MOODLE_COOKIES', true); This has a much lower barrier to adoption that readonly sessions and just works

**Comment by marinaglancy** [comment]
Hi Brendan, this should be addressed now. Thanks for suggestion, I did not know about require_user_key_login()
